SHOW WAREHOUSES;

CREATE WAREHOUSE DEMO_WAREHOUSE
WITH WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = "Demo warehouse created for teaching purposes"



SHOW WAREHOUSES;


--decrease cost by lowering time before auto-suspension
ALTER WAREHOUSE DEMO_WAREHOUSE
SET AUTO_SUSPEND = 60;

SHOW WAREHOUSES;


DROP WAREHOUSE DEMO_WAREHOUSE;

SHOW WAREHOUSES;